<?php
$config = array(
    'debug' => 0,
    'Security' => array(
        'level' => 'medium',
        'salt' => 'Remplacezmoi',
        'cipherSeed' => '',
        'auth_enforced' => false,
        'rest_client_baseurl' => 'http://localhost',
        'rest_client_port' => '',
        'encryption_key' => 'Remplacezmoi',
    ),
    'MISP' => array(
        'baseurl' => 'http://localhost',
        'external_baseurl' => 'http://localhost',
        'email' => 'admin@admin.test',
        'contact' => 'admin@admin.test',
        'org' => 'ORGNAME',
        'live' => true,
        'language' => 'fr',
        'redis_host' => 'redis',
        'redis_port' => 6379,
        'redis_database' => 13,
        'ssdeep' => false,
        'pymisp' => false,
        'attachment_scan_module' => false,
        'warning_for_all' => true,
    ),
    'GnuPG' => array(
        'onlyencrypted' => false,
        'email' => '',
        'homedir' => '',
        'password' => '',
        'binary' => '/usr/bin/gpg',
    ),
    'Proxy' => array(
        'host' => '',
        'port' => '',
        'method' => '',
        'user' => '',
        'password' => '',
    ),
    'Database' => array(
        'host' => 'db',
        'port' => 3306,
        'database' => 'misp',
        'username' => 'misp',
        'password' => 'misp',
        'encoding' => 'utf8',
    ),
);
